[[doing]]
title = "Software Development"
icon = "./config/assets/icons/laptop-code.svg"
text = "High-quality development of software at the professional level."

[[doing]]
title = "Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using Python to enhance efficiency and productivity."

[[doing]]
title = "DevSevOps"
icon = "./config/assets/icons/mobile.svg"
text = "Professional development of automation CICD process."

[[doing]]
title = "Solution Architect"
icon = "./config/assets/icons/compass.svg"
text = "Analyze business problems, identify technical requirements, and create detailed plans for integrating new systems and technologies."