[[doing]]
title = "Software Development"
icon = "./config/assets/icons/laptop-code.svg"
text = "High-quality development of software at the professional level."

[[doing]]
title = "Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using Python to enhance efficiency and productivity."

[[doing]]
title = "DevSevOps"
icon = "./config/assets/icons/mobile.svg"
text = "Professional development of automation CICD to the next level."

[[doing]]
title = "Solution Architect"
icon = "./config/assets/icons/compass.svg"
text = "Analyze business problems and create detailed plans for integrating new systems and technologies."