############## Education config #################
#################################################
[[education]]
title = "Gunadarma University"
timeline = "2007 — 2011"
description = "A Bachelor of Science in Computer Systems (B.Sc. in Computer Systems) is an undergraduate program designed to equip students with the foundational knowledge and practical skills needed to design, implement, and manage computer systems. This multidisciplinary field blends principles of computer science, electrical engineering, and information technology to develop comprehensive solutions for various computing needs."

[[education]]
title = "Gunadarma University"
timeline = "20016 — 2018"
description = "A Master of Science in Business Information Systems (M.Sc. in Business Information Systems) is a graduate program designed to prepare students for advanced roles at the intersection of business and technology. This interdisciplinary field integrates principles of information technology, management, and business strategy to develop, implement, and manage information systems that support business operations and decision-making."


############## Experience config ################
#################################################
[[experience]]
title = "IT Core Banking Application T24 at PT Rabobank International Indonesia"
timeline = "2013 — 2017"
description = "Windows server, MySQL Server, JBoss, T24 corebanking system, Alaric, Solarwind"

[[experience]]
title = "System Engineer and Release Management at Mekar Investama Sampoerna"
timeline = "2017 — 2019"
description = "Docker, MySQL Server, Jenkins, AWS, Python, Github, Metabase, Sentry, Rancer, Slack."

[[experience]]
title = "Digital Banking Development Operation Specialist at Jenius"
timeline = "2019 — 2021"
description = "Openshift K8s, NewRelic, Splunk, Minio, NXRM, Jenkins, Bitbucket, React, NodeJS, MongoDB, GraphQL, AWS, Slack."

[[experience]]
title = "Digital Ecosystem Development Specialist at CT Corp Digital"
timeline = "2021 — 2022"
description = "GCP, GWS, Datadog, Jenkins, Gitlab, Docker, Quarkus, MySQL Server, Keycloak, Matermost."

[[experience]]
title = "Manager IT Infrastructure and Operations at Briix Financial Technology"
timeline = "2021 — Present"
description = "GCP, GWS, Github, Signoz, Docker, Firebase, Flutter, Quarkus, VueJS."

############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "IT Service Management"
value = "90%"

[[skill]]
title = "IT Operations"
value = "95%"

[[skill]]
title = "Software Development"
value = "90%"

[[skill]]
title = "Leadership"
value = "95%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "English"
value = "90%"