############### Section config ##################
#################################################
title = "Soft Skills"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "Fast Learner"
icon = "./config/assets/icons/bolt.svg"
text = "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."

[[skills]]
title = "Leadership "
icon = "./config/assets/icons/user.svg"
text = "My approach to leadership is grounded in empathy and accountability, empowering my team to achieve their best while maintaining a culture of trust and respect."

[[skills]]
title = "Problem Solving"
icon = "./config/assets/icons/gear.svg"
text = "I am creative and efficient in identifying and solving technical problems."

[[skills]]
title = "Effective Communication"
icon = "./config/assets/icons/comment.svg"
text = "I have the skill to convey ideas clearly and concisely, both technically and non-technically."
